"""
FinSight AI — Pydantic schemas for the report / investment memo endpoint.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


class SWOTAnalysis(BaseModel):
    """SWOT analysis structure."""

    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    opportunities: list[str] = Field(default_factory=list)
    threats: list[str] = Field(default_factory=list)


class InvestmentMemo(BaseModel):
    """Structured investment memo generated by the AI agent."""

    summary: str = ""
    bull_case: list[str] = Field(default_factory=list)
    bear_case: list[str] = Field(default_factory=list)
    swot: SWOTAnalysis = Field(default_factory=SWOTAnalysis)
    guidance: str = ""
    recommendation: str = "HOLD"  # BUY | HOLD | SELL
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


class ReportResponse(BaseModel):
    """Full report response wrapping the memo with metadata."""

    symbol: str
    memo: InvestmentMemo
    step_log: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
